import type { ScrollType, SourceType, CalendarType } from "./types";

export interface PremadeScroll {
  id: string;
  title: string;
  description: string;
  emoji: string;
  color: string; // cover color for the 3D book
  scroll_type: ScrollType;
  source_type: SourceType | "mixed";
  config: Record<string, unknown>;
  category: "popular" | "mishnayos" | "gemara" | "tanakh" | "daily";
}

export const premadeScrolls: PremadeScroll[] = [
  // ── Daily / Calendar ──
  {
    id: "daf-yomi",
    title: "Daf Yomi",
    description: "A page of Gemara every day",
    emoji: "📅",
    color: "#1a3a5c",
    scroll_type: "calendar",
    source_type: "gemara",
    config: { calendarType: "daf_yomi" as CalendarType },
    category: "daily",
  },
  {
    id: "daily-mishnah",
    title: "Daily Mishnah",
    description: "Follow the worldwide Mishnah cycle",
    emoji: "🌍",
    color: "#2d5016",
    scroll_type: "calendar",
    source_type: "mishnayos",
    config: { calendarType: "daily_mishnah" as CalendarType },
    category: "daily",
  },
  {
    id: "weekly-parsha",
    title: "Weekly Parsha",
    description: "This week's Torah portion",
    emoji: "🕯️",
    color: "#5c1a1a",
    scroll_type: "calendar",
    source_type: "chumash",
    config: { calendarType: "parsha" as CalendarType },
    category: "daily",
  },

  // ── Popular Mishnayos ──
  {
    id: "pirkei-avos",
    title: "Pirkei Avos",
    description: "Ethics of the Fathers — timeless wisdom",
    emoji: "💎",
    color: "#4a1942",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Pirkei_Avot", sourceType: "mishnayos" },
    category: "popular",
  },
  {
    id: "mishnah-berachos",
    title: "Mishnah Berachos",
    description: "Laws of blessings and prayer",
    emoji: "🙏",
    color: "#1a3352",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Mishnah_Berakhot", sourceType: "mishnayos" },
    category: "mishnayos",
  },
  {
    id: "mishnah-shabbos",
    title: "Mishnah Shabbos",
    description: "Laws of Shabbat — 24 chapters",
    emoji: "✨",
    color: "#2a2a4a",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Mishnah_Shabbat", sourceType: "mishnayos" },
    category: "mishnayos",
  },
  {
    id: "mishnah-pesachim",
    title: "Mishnah Pesachim",
    description: "Laws of Passover and the Seder",
    emoji: "🍷",
    color: "#5c1a2a",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Mishnah_Pesachim", sourceType: "mishnayos" },
    category: "mishnayos",
  },
  {
    id: "mishnah-sanhedrin",
    title: "Mishnah Sanhedrin",
    description: "Courts, justice, and fundamental beliefs",
    emoji: "⚖️",
    color: "#3d2b1a",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Mishnah_Sanhedrin", sourceType: "mishnayos" },
    category: "mishnayos",
  },
  {
    id: "mishnah-sukkah",
    title: "Mishnah Sukkah",
    description: "Laws of the Sukkah and Lulav",
    emoji: "🌿",
    color: "#1a4a2a",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Mishnah_Sukkah", sourceType: "mishnayos" },
    category: "mishnayos",
  },
  {
    id: "mishnah-megillah",
    title: "Mishnah Megillah",
    description: "Laws of reading the Megillah",
    emoji: "📜",
    color: "#4a3a1a",
    scroll_type: "structured",
    source_type: "mishnayos",
    config: { slug: "Mishnah_Megillah", sourceType: "mishnayos" },
    category: "mishnayos",
  },

  // ── Gemara ──
  {
    id: "gemara-berachos",
    title: "Gemara Berachos",
    description: "64 dapim on blessings and prayer",
    emoji: "📖",
    color: "#0d2137",
    scroll_type: "structured",
    source_type: "gemara",
    config: { slug: "Berakhot", sourceType: "gemara" },
    category: "gemara",
  },
  {
    id: "gemara-shabbos",
    title: "Gemara Shabbos",
    description: "157 dapim — the classic masechet",
    emoji: "🕎",
    color: "#1a1a3d",
    scroll_type: "structured",
    source_type: "gemara",
    config: { slug: "Shabbat", sourceType: "gemara" },
    category: "gemara",
  },
  {
    id: "gemara-bava-metzia",
    title: "Gemara Bava Metzia",
    description: "Civil law, lost objects, and business",
    emoji: "🤝",
    color: "#2a1a0d",
    scroll_type: "structured",
    source_type: "gemara",
    config: { slug: "Bava_Metzia", sourceType: "gemara" },
    category: "gemara",
  },
  {
    id: "gemara-makkos",
    title: "Gemara Makkos",
    description: "Short masechet — just 24 dapim",
    emoji: "⚡",
    color: "#37210d",
    scroll_type: "structured",
    source_type: "gemara",
    config: { slug: "Makkot", sourceType: "gemara" },
    category: "gemara",
  },

  // ── Tanakh ──
  {
    id: "bereishis",
    title: "Bereishis",
    description: "The Book of Genesis — creation to Egypt",
    emoji: "🌅",
    color: "#1a2a4a",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Genesis", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "shemos",
    title: "Shemos",
    description: "Exodus — from slavery to Sinai",
    emoji: "🔥",
    color: "#4a1a0d",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Exodus", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "tehillim",
    title: "Tehillim",
    description: "150 chapters of Psalms",
    emoji: "🎵",
    color: "#2a1a4a",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Psalms", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "mishlei",
    title: "Mishlei",
    description: "Proverbs — King Solomon's wisdom",
    emoji: "👑",
    color: "#4a3a0d",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Proverbs", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "koheles",
    title: "Koheles",
    description: "Ecclesiastes — meaning and purpose",
    emoji: "🌙",
    color: "#1a2a2a",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Ecclesiastes", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "esther",
    title: "Megillas Esther",
    description: "The Purim story",
    emoji: "👸",
    color: "#4a1a3a",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Esther", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "rus",
    title: "Megillas Rus",
    description: "A story of loyalty and kindness",
    emoji: "🌾",
    color: "#3a4a1a",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Ruth", sourceType: "chumash" },
    category: "tanakh",
  },
  {
    id: "yonah",
    title: "Sefer Yonah",
    description: "The prophet and the whale",
    emoji: "🐋",
    color: "#0d2a3a",
    scroll_type: "structured",
    source_type: "chumash",
    config: { slug: "Jonah", sourceType: "chumash" },
    category: "tanakh",
  },
];
